CREATE TABLE IF NOT EXISTS publications (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT,
    url TEXT UNIQUE,
    publication_date TEXT,
    effective_date TEXT,
    status TEXT,
    raw_html TEXT,
    full_text TEXT,
    content_type TEXT,
    pdf_path TEXT,
    pdf_hash TEXT,
    primary_domain TEXT,
    health_score INTEGER,
    fiscal_score INTEGER,
    retail_score INTEGER,
    border_region_score INTEGER,
    currency_score INTEGER,
    operational_obligation_score INTEGER,
    invoicing_score INTEGER,
    tax_reporting_score INTEGER,
    inventory_score INTEGER,
    accounting_score INTEGER,
    pos_score INTEGER,
    impacted_module TEXT,
    severity TEXT,
    impact_flag INTEGER,
    impact_reason TEXT,
    analyzed_at TEXT
);
